import { Box, Typography } from "@mui/material";
import Grid from "@mui/material/Unstable_Grid2";
import Head from "next/head";
import Image from "next/image";
import imageAboutDark from "public/images/image-about-dark.jpg";
import imageAboutLight from "public/images/image-about-light.jpg";
import Carousel from "components/Carousel";
import DrawerAppBar from "components/DrawerAppBar";

export default function Home() {
  return (
    <>
      <Head>
        <title>FrontendMentor</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Grid container>
          <Grid xs={12} md={12}>
            <Box sx={{ height: { xs: "770px", md: "66.75vh" } }}>
              <DrawerAppBar />
              <Carousel /> {/* height= "66.75vh" */}
            </Box>
          </Grid>
          <Grid xs={12} md={3.5}>
            <Box
              sx={{
                height: { xs: "63.47vw", md: "33.25vh" },
                overflow: "hidden",
              }}
            >
              <Image src={imageAboutDark} alt="" className="imageAbout" />
            </Box>
          </Grid>
          <Grid xs={12} md={4.83}>
            <Box
              sx={{
                px: { xs: "8.53vw", md: "8.275%" },
                height: { xs: "80.8vw", md: "100%" },
                display: "flex",
                flexDirection: "column",
                justifyContent: "center",
              }}
            >
              <Typography
                variant="h3"
                sx={{
                  textTransform: "uppercase",
                  fontSize: "0.9rem",
                  fontWeight: "700",
                  letterSpacing: "4.2px",
                  marginBottom: "0.875rem",
                }}
              >
                About Our Furniture
              </Typography>
              <Typography
                variant="body2"
                sx={{
                  textAlign: { xs: "left", md: "justify" },
                  fontSize: { xs: "13.5px", md: "13.5px" },
                  color: "var(--DarkGray)",
                }}
              >
                Our multifunctional collection blends design and function to
                suit your individual taste. Make each room unique, or pick a
                cohesive theme that best express your interests and whatinspires
                you. Find the furniture pieces you need, from traditional to
                contemporary styles or anything in between. Product specialists
                are available to help you create your dream space.
              </Typography>
            </Box>
          </Grid>
          <Grid xs={12} md={3.67}>
            <Box
              sx={{
                height: { xs: "60.8vw", md: "33.25vh" },
                overflow: "hidden",
              }}
            >
              <Image src={imageAboutLight} alt="" className="imageAbout" />
            </Box>
          </Grid>
        </Grid>
      </main>
    </>
  );
}
